name: taQs
description: A new Weather App Project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc:
  bloc:
  cubit:
  dio:
  intl:
  lottie:
  conditional_builder_null_safety:
  flutter_advanced_drawer:
  geolocator: ^9.0.1
  shared_preferences:
  internet_connection_checker:



dev_dependencies:
  flutter_launcher_icons:

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/taqs_logo.png"

  flutter_test:
    sdk: flutter

flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
